### ISSUE TITLE
Test demo workflow RVE_extrusion_EBSD

### ISSUE THREAD

**Issue by gcapes** [hpcflow/matflow-new#291]

**Comment by gcapes** [comment]
The `RVE_extrusion_EBSD` workflow fails with an out-of-memory error on the `simulate_VE_loading_damask` task.

@aplowman I know when requesting multiple cores for this, it needs to be a factor of something for it to work correctly with MPI. I can't figure out from the workflow file what this is though :)

If DAMASK requires MPI, I'm wondering whether we could/should just add a resources block for that task, maybe with a comment explaining how to work out the permitted number of cores?

**Comment by gcapes** [comment]
This needs to be the size of geometry in z direction. Look at vtk file (xml) - should be able to see the dimensions here.

**Comment by gcapes** [comment]
Once we know how many ranks are needed, update the demo workflow  file.

**Comment by gcapes** [comment]
I guess the file in question is `geom.vti`, but I couldn't really tell what I was looking for.  Is is the depth value in the schema below? That would also serve as an easy way to document the required num_cores in the doc string, if that is in fact the case :)

```
  - schema: generate_volume_element_extrusion
    inputs:
      depth: 8
      image_axes: ["y", "x"]
      homog_label: SX
      phase_label: Ti
```

I've submitted the workflow with 8 cores - just waiting for it to run.
