### ISSUE TITLE
generate seeds orientations used in simulate_VE rather than those specified by a following task

### ISSUE THREAD

**Issue by Gbowker** [hpcflow/matflow-new#325]
I am trying to simply generate a VE, generate a texture, and simulate the VE with the defined texture, NOT a random one:

```yaml
doc:
  - >
    A Ti-alpha crystal plasticity simulation using DAMASK. A volume element generated from a
    random voronoi tessellation with a strong basal ND prism RD texture is loaded in plane
    strain rolling, using hot Ti64 HCP single crystal parameters.

tasks:
  - schema: generate_microstructure_seeds_from_random # task 0
    inputs:
      VE_size: [1, 1, 1]
      num_grains: 2000
      phase_label: Ti-alpha
#   outputs: microstructure_seeds


  - schema: generate_volume_element_from_voronoi # task 1
    inputs:
      homog_label: SX
      VE_grid_size: [128, 128, 128]
#   outputs: volume_element


  - schema: sample_texture_from_model_ODF_mtex # task 2
    inputs:
      crystal_symmetry: hexagonal
      specimen_symmetry: orthorhombic
      num_orientations: 2000
      ODF_components:
        - type: unimodal
          component_fraction: 1 # component fractions must sum to 1!
          modal_orientation_euler: [0, 0, 0] # in Bunge/degrees/MTEX hex alignment (y//b)
          halfwidth: 5
      compile: false
#   outputs:
#     orientations: (HDF5 file)


  - schema: visualise_orientations_pole_figure_mtex # task 3
    input_sources:
      orientations: task.sample_texture_from_model_ODF_mtex
    inputs:
      crystal_symmetry: hexagonal
      pole_figure_directions:
        - [0, 0, 0, 2]
        - [1, 0, -1, 0]
        - [1, 1, -2, 0]
      use_contours: false
      compile: false

  - schema: simulate_VE_loading_damask # task 4
    input_sources:
      volume_element: task.sample_texture_from_model_ODF_mtex
    inputs:
      load_case::plane_strain:
        total_time: 2
        num_increments: 20
        direction: zy
        target_def_grad_rate: -0.1
        dump_frequency: 1
      homogenization:
        SX:
          mechanical: { type: "pass" }
          N_constituents: 1
      damask_phases:
        Ti-alpha:
          lattice: hP
          c/a: 1.62350 # from Tromans 2011, Elastic Anisotropy of HCP Metal Crystals and Polycrystals
          rho: 1740.0
          mechanical:
            output: [F, P, F_e, F_p, L_p, O]
            elastic:
              type: Hooke
              C_11: 59.3e9
              C_12: 25.7e9
              C_13: 21.4e9
              C_33: 61.5e9
              C_44: 16.4e9
            plastic:
              type: phenopowerlaw
              references:
                - C. Zambaldi et al.,
                  Journal of Materials Research 27(1):356-367, 2021,
                  https://doi.org/10.1557/jmr.2011.334
                - L. Wang et al.,
                  Acta Materialia 132:598-610, 2017,
                  https://doi.org/10.1016/j.actamat.2017.05.015
              N_sl: [3, 3, 0, 12] # basal 3, prism1 3, prism2 -, pyr<c+a> 12
              a_sl: 2.0                                           # hardening law exponent
              a_tol_xi: 1.0                                       # ?
              dot_gamma_0_sl: 0.1                               # initial shear rate
              h_sl-sl: [1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0] # unused entries are indicated by -1.0
              h_0_sl-sl: 200e6                                    # initial hardening slsl interaction
              n_sl: 5 # (semiatin2001, Dunst1996, Lebensohn1997)  # stress exponent 1/m (m=strain rate sensitivity)
              xi_0_sl: [84e+6, 140e+6, 0, 490e+6]  # hot estimate    # CRSS initial (MPa)
              xi_inf_sl: [104e+6, 160e+6, 0, 510e+6] # hot estimate   # CRSS hardened

      damask_post_processing:
        - name: add_IPF_color
          args: { l: [1, 0, 0] }
        - name: add_IPF_color
          args: { l: [0, 1, 0] }
        - name: add_IPF_color
          args: { l: [1, 0, 0] }
      VE_response_data:
        phase_data:
          - phase_name: Ti-alpha
            field_name: O
            out_name: Ti-alpha_O
        field_data:
          - field_name: phase
          - field_name: O
      damask_viz:
        fields:
          [IPFcolor_(1 0 0), IPFcolor_(0 1 0), IPFcolor_(0 0 1), phase]
        increments:
          - step: 1
```

Running this, task 3 pole figure show the defined texture:
![Image](https://github.com/user-attachments/assets/9dbb1adc-0029-44c8-a515-b5820113b7f1)

However post-processing the texture from the simulation shows that it started with a random texture:
![Image](https://github.com/user-attachments/assets/28eb1d3d-0cd3-4262-afef-c7f32421a543)
![Image](https://github.com/user-attachments/assets/756a054f-27c3-4791-91fb-ef5c7cd1ab38)
![Image](https://github.com/user-attachments/assets/0d2585d7-d029-473b-8c88-3e59dfd4dc41)

So clearly the simulate_VE_task has taken the random orientations produced by task 0 rather than the ones defined by task 2.
I've made an attempt to remedy this in the next comment...

**Comment by Gbowker** [comment]
My solution was to define an objective block which runs a very basic python script.
This python script takes `volume_element` and `orientations` dicts as inputs.
The `volume_element` dict is prodcued by generate seeds and generate voronoi, and contains an `orientations` dict which is populated by random orientations by these tasks.

The `orientations` dict is produced by `sample_texture_from_model_ODF_mtex` or any other task that might otherwise define a texture such as `sample_texture_from_CTF_file` for example.
I want to replace the `orientations` dict in `volume_element` with the one that is defined by the task `sample_texture_from_model_ODF_mtex` so that the `simulate_VE_loading` task uses the desired texture.

```yaml
# define task to replace oris with generated ones
template_components:
  task_schemas:
  - objective: replace_oris
    inputs:
      - parameter: volume_element
      - parameter: orientations
    actions:
    - script: <<script:/mnt/iusers01/jf01/y15576gb/scratch/replace_oris.py>>
      script_data_in: direct
      script_data_out: direct
      script_exe: python_script
      environments:
      - scope:
          type: any
        environment: damask_parse_env
    outputs:
      - parameter: volume_element

tasks: # NOTE HOW THIS COMES BEFORE TASKS

# ... tasks 0, 1, 2, 3, described above... #

  - schema: replace_oris # new task 4. sim_VE_loading now task 5.
    input_sources:
      orientations: task.sample_texture_from_model_ODF_mtex
      volume_element: task.generate_volume_element_from_voronoi
#   outputs: volume_element

```

This calls this `replace_oris.py` :
```python
def replace_oris(volume_element: dict, orientations: dict) -> dict:
    """
    replace orientations of volume element with defined orientations
    """
    volume_element['orientations'] = orientations

    out = {'volume_element': volume_element}

    return out
```

Using `matflow go` with this submits the jobs to queue and successfully runs tasks 0, 1, 2, 3, but fails on this newly defined task with the error found in `tube-rolling_DAMASK_Ti-alpha_0002ND1010RD_2025-02-19_112837/artifacts/submissions/0/js_2.sh.e5555166` being:
```unix
Traceback (most recent call last):
  File "/net/scratch2/y15576gb/tube-rolling_DAMASK_Ti-alpha_0002ND1010RD_2025-02-19_112837/execute/task_4_replace_oris/e_0/r_0/replace_oris.py", line 43, in <module>
    wk.set_parameter_value(param_id=EAR.data_idx[name_i], value=out_i)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/log.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/core/workflow.py", line 2307, in set_parameter_value
    with self.batch_update():
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/core/workflow.py", line 1666, in batch_update
    self._store._pending.commit_all()
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/log.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/pending.py", line 160, in commit_all
    getattr(self, meth)()
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/log.py", line 43, in wrapper
    return func(*args, **kwargs)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/pending.py", line 444, in commit_parameters
    self.store._set_parameter_values(self.set_parameters)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/zarr.py", line 761, in _set_parameter_values
    param_i.encode(
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/zarr.py", line 305, in encode
    return super().encode(root_group=root_group, arr_path=arr_path)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/base.py", line 604, in encode
    return self._encode(obj=self.data, **kwargs)
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/base.py", line 659, in _encode
    encoded = self._encode(
  File "/mnt/iusers01/jf01/y15576gb/.conda/envs/damask-venv/lib/python3.10/site-packages/hpcflow/sdk/persistence/base.py", line 683, in _encode
    raise ValueError(
ValueError: Parameter data with type <class 'zarr.core.Array'> cannot be serialised into a ZarrStoreParameter: <zarr.core.Array '/parameters/arrays/param_13/arr_0' (3,) int64 read-only>.
```

So what have I done wrong? @gcapes ?

**Comment by gcapes** [comment]
I'm afraid I can't see anything wrong with your workflow files - the approach makes sense if I've correctly understood that a volume element contains orientations.
The zarr error looks like trying to output an invalid data type, but you're just replacing the orientations in the volume element  so you're not creating a new data type?
I think we need input from @aplowman ?

**Comment by gcapes** [comment]
Or maybe @dkfellows might be able to help?

**Comment by aplowman** [comment]
This is because we don't support saving Zarr arrays to the store yet. If you load an array as part of your new task, and then include it as part of an output parameter, you'll need to cast it to a Numpy array, i.e. `arr = np.array(arr)`.

**Comment by Gbowker** [comment]
--- So you've stored everything as a Zarr array? Why? Arent np arrays efficient enough? ---

So I just need to specify that `volume_element['orientations']['quaternions']` is a numpy array not a zarr array? Like this?
```python
def replace_oris(volume_element: dict, orientations: dict) -> dict:
    """
    replace orientations of volume element with defined orientations
    """
    volume_element['orientations']['quaternions'] = np.array(orientations['quaternions'])
    out = {'volume_element': volume_element}
    return out
```

**Comment by Gbowker** [comment]
Furthermore why could the `simulate_VE` task use the orientations from the `random-seeds` task if they were zarr arrays? Are they cast to numpy arrays in the `simulate_VE` task? IMO its not necessary for texture when it can be extracted from the simulation anyway?

**Comment by aplowman** [comment]
Numpy arrays are used as in-memory representations of array data. We need persistent (on disk) representations, so the arrays are still there after you've rebooted :)

You'll need to cast all array items to Numpy arrays. There are probably other keys inside `volume_element` that are also arrays. I would recommend, loading a `volume_element` parameter from a workflow within a Jupyter notebook and checking to see which keys needs to be cast to Numpy arrays. 

I agree this is annoying behaviour, hopefully we can fix it soon.

> Furthermore why could the simulate_VE task use the orientations from the random-seeds task if they were zarr arrays? Are they cast to numpy arrays in the simulate_VE task?

The `simulate_VE_task` is effectively casting the orientations into a Numpy array. This happens automatically whenever you slice the array (e.g. `arr[:10]`).

>  IMO its not necessary for texture when it can be extracted from the simulation anyway?

I don't follow. Can you expand?

**Comment by Gbowker** [comment]
Results such as texture can be extracted from the simulation `geom_load.hdf5` using the damask library. Any saved orientations in the workflow used to build the model are only the same as the first increment of the simulation anyway, and whenever a user is using `simulate_VE` to predict texture evolution, they are interested in the texture that comes from the `simulate_VE` task, all others are made redunant?

**Comment by aplowman** [comment]
I see what you mean, but the original orientations are not redundant if you are interested in reproducibility and traceability, i.e. "how did the workflow manipulate the data to come to an answer?".

**Comment by Gbowker** [comment]
This has worked after adding the following to `replace_oris.py`:

```diff
+ import numpy array as np
def replace_oris(volume_element: dict, orientations: dict) -> dict:
    """
    replace orientations of volume element with defined orientations
    """
+    volume_element['grid_size'] = np.array(volume_element['grid_size'])
+    volume_element['element_material_idx'] = np.array(volume_element['element_material_idx'])
+    volume_element['constituent_material_idx'] = np.array(volume_element['constituent_material_idx'])
+    volume_element['constituent_material_fraction'] = np.array(volume_element['constituent_material_fraction'])
+    volume_element['constituent_phase_label'] = np.array(volume_element['constituent_phase_label'])
+    volume_element['constituent_orientation_idx'] = np.array(volume_element['constituent_orientation_idx'])
+    volume_element['material_homog'] = np.array(volume_element['material_homog'])
+    volume_element['orientations']['quaternions'] = np.array(orientations.data)
    out = {'volume_element': volume_element}
    return out
```

This issue can be closed, however it still isnt permenantly solved - it needs a solution which is written into `simulate_VE_loading` so that it always recognises and uses the *latest* texture defined in the workflow.

**Comment by gcapes** [comment]
Could that code be added into the `simulate_VE_loading` task so that this is a permanent fix?

It could go as a preliminary action to update the `orientations` in the `volume_element` before the input file generators use the `volume_element` as input?

So just before this line https://github.com/hpcflow/matflow-new/blob/develop/matflow/data/template_components/task_schemas.yaml#L548

Something like
```
actions:
    - environments:
        - scope:
            type: processing
          environment: damask_parse_env
        - scope:
            type: main
          environment: damask_env
      script: <<update_orientations.py>>
      script_data_in: direct
      script_data_out: direct
      script_exe: python_script
      input_file_generators:
        - input_file: damask_geom_file
          from_inputs: [volume_element]
          script: <<script:damask/write_geom.py>>
        - input_file: damask_load_file
          from_inputs: [load_case, damask_solver]
          script: <<script:damask/write_load.py>>
```

I'm not sure whether there's always going to be `orientations` as an output parameter earlier in the workflow, so the `orientations` parameter for the `update_orientations.py` script could be optional and just return the same `volume_element` as the default case.
