### ISSUE TITLE
Add tutorial for running small demo workflow on local machine

### ISSUE THREAD

**Issue by SJaffa** [hpcflow/matflow-new#327]
For people who are new to MatFlow there are a lot of concepts to pick up in order to understand the documentation and effectively set up your own workflow. A good way to learn some of the concepts without extra cognitive load might be to follow a [tutorial](https://diataxis.fr/tutorials/) to run a minimal workflow on your own laptop. This would have very detailed instructions and no decisions for the user to make.

This can help people learn the general purpose of each step in the setup, some of the jargon, and make sure they can see the whole process to the end. This should make it much easier when trying to install on a HPC cluster.

This should be linked from the landing page of the [documentation](https://docs.matflow.io/stable/).

**Comment by SJaffa** [comment]
@Gbowker which workflows would be suitable for running on a laptop?

**Comment by Gbowker** [comment]
Hi @SJaffa so since I said this I have realised that only the tasks which use python in practace anyone could use, becuase MTEX requires a matlab licence and Damask requires a powerful computer. The best demo workflows in this case would be ones in which just use python. BUT the only one at the moment is `read_tensile_test_CSV.yaml`. I think there should be one which just generates microstructure seeds, and generates a volume element using these in python. Then users can visualise the output 3D .vti file using paraview, a free 3D data visualisation program.

Proposed easy to run demo-workflow:
`generate_volume_element.yaml`

```yaml
  - schema: generate_microstructure_seeds_from_random
    inputs:
      VE_size: [1, 1, 1]
      num_grains: 4
      phase_label: demo

  - schema: generate_volume_element_from_voronoi
    inputs:
      homog_label: SX
      VE_grid_size: [8, 8, 8]

  - schema: visualise_volume_element
```

@gcapes what do you think?
