### ISSUE TITLE
Update environment definitions for new hpcflow

### ISSUE THREAD

**Issue by gcapes** [hpcflow/matflow-new#354]
From an email discussion with Adam, I have this advice which fixes my hello-world example:

You'll need to change any python_script environment executables from:

```
      - label: python_script
        instances:
          - command: python <<script_name>> <<args>>
            ...
```

...to:

```
      - label: python_script
        instances:
          - command: python "<<script_path>>" <<args>>
            ...
```

i.e. change `<<script_name>>` to `"<<script_path>>"` (with double quotes).

Where should these environment definitions go? Theres's some in my [PR](https://github.com/hpcflow/matflow-new/pull/333), but also some here: https://docs.matflow.io/stable/development/environments.html
