### ISSUE TITLE
Add user guide for setting up MatFlow for CSF3/SLURM (environment definitions/config/python package versions)

### ISSUE THREAD

**Issue by gcapes** [hpcflow/matflow-new#376]
As a user of MatFlow @ UoM, I would like to know how to set up MatFlow from scratch so that the demo workflows run.

- [x] Move and update existing environment definitions from the "development" tab of the MatFlow docs to the "install" tab
- [x] Detail how to pull a config file from the MatFlow configs repo
- [x] Define any specific python package versions that are needed for e.g. damask
- [x] Explain that currently the slurm partition isn't automatically selected based on the requested resources, and must be manually defined in the workflow file like this
   ```yaml
  resources:
    any:
      scheduler_args:
        directives:
          --time: 00:30:00
          --partition: ukaea-spr
   ```
- [x] Explain how to set default job time limit per https://github.com/hpcflow/matflow-new/issues/352#issuecomment-2838080924
