### ISSUE TITLE
Support CIPHER

### ISSUE THREAD

**Issue by aplowman** [hpcflow/matflow-new#392]
- Old-matflow extension package: https://github.com/LightForm-group/matflow-cipher/tree/main
- Example workflow: https://github.com/LightForm-group/UoM-CSF-matflow/blob/master/workflows/grain_growth_volume_element.yml
- Simulation task schema: https://github.com/LightForm-group/UoM-CSF-matflow/blob/f1ca8c9b61471e0f7b45aec2786c1dae1eff5445/task_schemas.yml#L1801
- Input preparation task scheam: https://github.com/LightForm-group/UoM-CSF-matflow/blob/f1ca8c9b61471e0f7b45aec2786c1dae1eff5445/task_schemas.yml#L1752

Software definition from CSF3 (akin to environments): 
```yaml
cipher:
  instance_defaults:
    version_info:
      cipher_parse:
        version: '0.5.1a0'
    executable: cipher.exe
    env: |
      module load apps/binapps/anaconda3/2020.07
      module load apps/binapps/paraview/5.6.0
      source activate /mnt/eps01-rds/jf01-home01/shared/.conda/cipher_parse_develop_env
      export HDF5_USE_FILE_LOCKING=FALSE
      export OMP_NUM_THREADS=1
      source /mnt/eps01-rds/jf01-home01/shared/software/cipher_env.sh
    task_preparation:
      env: export HDF5_USE_FILE_LOCKING=FALSE
    task_processing:
      env: export HDF5_USE_FILE_LOCKING=FALSE
  instances:
    - num_cores: 1
    - num_cores: [2, 32, 1]
      required_scheduler_options:
        pe: smp.pe
```

**Comment by gcapes** [comment]
Aidan's workflow file

```yaml
name: grain_growth_from_VE_dream3D_nucleus_with_MTEX_texture_binned
run_options:
  l: short

archive: dropbox

tasks:

    # rotated cube texture for the sub-grain matrix:
  - name: sample_texture
    method: from_model_ODF
    software: mtex
    context: phase_1
    base:
      num_orientations: 1000
      crystal_symmetry: cubic
      specimen_symmetry: orthorhombic
      ODF_components:
        - type: unimodal
          component_fraction: 1.0 
          modal_orientation_HKL: [0, 0, 1]
          modal_orientation_UVW: [1, 1, 0]
          halfwidth: 3

  # within gamma-fibre for the nucleus:
  - name: sample_texture
    method: from_model_ODF
    software: mtex
    context: phase_2
    base:
      num_orientations: 100
      crystal_symmetry: cubic
      specimen_symmetry: orthorhombic
      ODF_components:
        - type: unimodal
          component_fraction: 1.0 
          modal_orientation_HKL: [1, 1, 1]
          modal_orientation_UVW: [1, 1, 2]
          halfwidth: 3

  - name: visualise_orientations
    method: pole_figure
    software: mtex
    context: phase_1
    base:
      crystal_symmetry: cubic
      pole_figure_directions:
        - [0, 0, 1]
        - [1, 0, 1]
        - [1, 1, 1]
      use_contours: false

  - name: visualise_orientations
    method: pole_figure
    software: mtex
    context: phase_2
    base:
      crystal_symmetry: cubic
      pole_figure_directions:
        - [0, 0, 1]
        - [1, 0, 1]
        - [1, 1, 1]
      use_contours: false

  - name: generate_volume_element
    method: from_statistics_dual_phase_orientations
    software: Dream3D
    base:
      grid_size: [512, 512, 1]
      resolution: [1, 1, 1] # side length is 512
      periodic: false
      phase_statistics:
        - type: primary
          name: sub-grain-matrix
          crystal_structure: cubic
          volume_fraction: 1.0
          size_distribution:
            ESD_mean: 10
            ESD_log_stddev: 0.03
            num_bins: 15
        - type: precipitate
          name: nuclei
          crystal_structure: cubic
          volume_fraction: 0.0
          size_distribution:
            ESD_mean: 2
            ESD_log_stddev: 0.1
            num_bins: 15
          number_fraction_on_boundary: 1
          radial_distribution_function:
            min_distance: 10
            max_distance: 80
            num_bins: 50
            box_size: [100, 100, 100]
      precipitates:
        - phase_number: 2
          position: [256, 256, 0.5]
          major_semi_axis_length: 45
          mid_semi_axis_length: 45
          minor_semi_axis_length: 45
          euler_angle: [0, 0, 0]

  - name: visualise_volume_element
    method: VTK
    software: damask

  - name: generate_phase_field_input
    method: from_volume_element
    software: cipher
    run_options:
      l: short
      num_cores: 2
    base:
      materials:
        - name: sub-grain-matrix
          properties:
            chemicalenergy: none
            molarvolume: 1e-5
            temperature0: 500.0
        - name: nuclei
          properties:
            chemicalenergy: none
            molarvolume: 1e-5
            temperature0: 500.0
      interfaces:
        - materials: [sub-grain-matrix, sub-grain-matrix] 
          properties:
            width: 4.0
            energy:
              e0: 1.0e+8
            mobility:
              m0: 3.333e-11
        - materials: [nuclei, nuclei] 
          properties:
            width: 4.0
            energy:
              e0: 1.0e+8
            mobility:
              m0: 10.0e-11
        - materials: [sub-grain-matrix, nuclei] 
          properties:
            width: 4.0
            energy:
              e0: 2.0e+8
            mobility:
              m0: 10.0e-11
      components: [ti]
      outputs: [phaseid, matid, interfaceid, 0_phi]
      solution_parameters:
        abstol: 0.0001
        amrinterval: 25
        initblocksize: [1, 1]
        initcoarsen: 9
        initrefine: 9
        interpolation: cubic
        maxnrefine: 9
        minnrefine: 0
        outfile: out
        outputfreq: 100
        petscoptions: -ts_adapt_monitor -ts_rk_type 2a
        random_seed: 1579993586
        reltol: 0.0001
        time: 40_000
      interface_binning: # specify one or both of energy_range/mobility_range:
        base_interface_name: [sub-grain-matrix-sub-grain-matrix, sub-grain-matrix-nuclei]
        theta_max: 50
        bin_width: 1
        energy_range: [0.1e+8, 2.0e+8]
        # mobility_range: [1.0e-11, 10.0e-11]
        # n: 1 # mobility parameter
        # B: 5 # mobility parameter

  - name: simulate_grain_growth
    method: phase_field
    software: cipher
    base:
      num_VTU_files: 4
      derive_outputs:
        - name: num_voxels_per_phase 
      save_outputs:
        - name: phaseid 
          time_interval: 5_000
        - name: matid
          number: 4
        - name: interfaceid
          number: 4
        - name: 0_phi
          number: 4
        - name: num_voxels_per_phase
          time_interval: 5_000
      delete_VTUs: true
    run_options:
      num_cores: 8
```
