### ISSUE TITLE
Get docker image with matflow and damask_grid

### ISSUE THREAD

**Issue by fherreazcue** [hpcflow/matflow-new#70]
Start from the latest [official DAMASK container](https://hub.docker.com/r/eisenforschung/damask-grid) and install matflow with single liner.
Ww want to be able to pass workflow template and have everything run in the container.

**Comment by aplowman** [comment]
We will need the image to have a conda environment for the pre-/post-processing steps. I have been using [micromamba](https://mamba.readthedocs.io/en/latest/installation.html#micromamba) instead of conda, because it's a lot smaller and meant to be faster, but mostly compatible with conda.

With conda/(micro)mamba installed, we'd need to create an environment and then install some packages with `pip` inside that environment:

```
micromamba create -n matflow_damask_parse_env python
micromamba activate matflow_damask_parse_env
pip install matflow-new damask-parse
```

(Note the matflow installed in this conda environment is separate from the matflow we'd install using the installer [which the user interacts with for submitting workflows]; in future what we install in this conda environment will be some sort of subset of what is currently matflow.)

We will then need this environment file (call it `envs.yaml`) placed in the `~/.matflow-new` directory:

```yaml
- name: damask_parse_env
  setup: |
    micromamba activate matflow_damask_parse_env
  executables:
    - label: python
       instances:
         - command: python
           num_cores: 1
           parallel_mode: null

- name: damask_env
  setup: null
  executables:
    - label: damask_grid
      instances:
        - command: DAMASK_grid
          num_cores: 1
          parallel_mode: null
```

And then this command to tell MatFlow about it:

```
matflow config append environment_sources envs.yaml`
```

Let's try and get this working first, then we can try and get DAMASK running with MPI as well.
