### ISSUE TITLE
`matflow show` command bug when task is spread over multiple non-scheduled jobscripts

### ISSUE THREAD

**Issue by aplowman** [hpcflow/matflow-new#80]
The workflow below has a `num_cores` sequence in the simulate task, which means the main action of this task is run via a distinct jobscript. The first two tasks run in jobscript 0; the first element of the simulate task runs in jobscript 1; the first three actions of the second element of the simulate task runs also in jobscript 1; the main action of the second element of the simulate task runs in jobscript 2 (with 2 cores); and finally the remaining actions (back to 1 core) of the second element of the simulate task runs in jobscript 3.

During execution, the `matflow show --full` command output looks like this:

![image](https://github.com/hpcflow/matflow-new/assets/5176471/19556505-0a01-4bfb-8db2-69e668a18c7e)

i.e. it shows duplicate markers for the second element.

After execution, they all go green:

![image](https://github.com/hpcflow/matflow-new/assets/5176471/f499de63-0731-4df6-ae1d-d93f6f6f164c)

```yaml
name: simple_damask
tasks:
  - schemas: [generate_microstructure_seeds_from_random]
    resources:
    inputs:
      VE_size: [1, 1, 1]
      num_grains: 100
      phase_label: Al

  - schemas: [generate_volume_element_from_random_voronoi]
    resources:
    inputs:
      homog_label: SX
      VE_grid_size: [32, 32, 32]

  - schemas: [simulate_VE_loading_damask]
    sequences:
      - path: resources.main.num_cores
        values: [1, 2]
        nesting_order: 1
    inputs:
      load_case::uniaxial:
        total_time: 5
        num_increments: 10
        direction: x
        target_strain_rate: 1.0e-3
      homogenization:
        SX:
          mechanical: { type: "pass" }
          N_constituents: 1
      damask_phases:
        Al:
          lattice: cF
          mechanical:
            output: [F, P, F_e, F_p, L_p, O]
            elastic:
              type: Hooke
              C_11: 106750000000
              C_12: 60410000000
              C_44: 28340000000
            plastic:
              type: phenopowerlaw
              N_sl: [12]
              a_sl: 2.25
              atol_xi: 1
              dot_gamma_0_sl: 0.001
              h_0_sl-sl: 75.0e+6
              h_sl-sl: [1, 1, 1.4, 1.4, 1.4, 1.4, 1.4]
              n_sl: 20
              output: [xi_sl]
              xi_0_sl: [31.0e+6]
              xi_inf_sl: [63.0e+6]
      damask_post_processing:
        - name: add_stress_Cauchy
          args: { P: P, F: F }
          opts: { add_Mises: true }
        - name: add_strain
          args: { F: F, t: V, m: 0 }
          opts: { add_Mises: true }
        - name: add_strain
          args: { F: F_p, t: V, m: 0 }
          opts: { add_Mises: true }
        - name: add_IPF_color
          args: { l: [0, 0, 1] }
      VE_response_data:
        phase_data:
          - field_name: sigma_vM
            phase_name: Al
            out_name: vol_avg_equivalent_stress
            transforms: [{ mean_along_axes: 1 }]
          - field_name: epsilon_V^0(F)_vM
            phase_name: Al
            out_name: vol_avg_equivalent_strain
            transforms: [{ mean_along_axes: 1 }]
          - field_name: epsilon_V^0(F_p)_vM
            phase_name: Al
            out_name: vol_avg_equivalent_plastic_strain
            transforms: [{ mean_along_axes: 1 }]
        field_data:
          - field_name: phase
          - field_name: O
        grain_data:
          - field_name: O
            increments: [{ values: [0, -1] }]
      damask_viz:
        fields: [F, F_p, P, sigma_vM, IPFcolor_(0 0 1), phase]
        increments: [{ start: 10, stop: 20, step: 2 }]

```
